FROM python:3.9-slim
WORKDIR /app
COPY storage_script.py /app/storage_script.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "/app/storage_script.py"]
