FROM python:3.9-slim
WORKDIR /app
COPY ingestion_script.py /app/ingestion_script.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "/app/ingestion_script.py"]
