FROM python:3.9-slim
WORKDIR /app
COPY transformation_script.py /app/transformation_script.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "/app/transformation_script.py"]
